### DISCUSSION TITLE
Private filesystem

### DISCUSSION THREAD

**Discussion by tinect** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#68] [Q&A] [answered]
Can I use bunnycdn for private filesystem?

**Comment by tinect** [comment, marked as answer]
Yes, you can. Please not, that there is no setting in the plugin, while the plugin configs are just reflecting the public part.

Please keep in mind you should NOT link the storage to a pull zone, while private filesystem should NOT be accessible by browser.

Create a `shopware.yml` within `config/packages` and your settings:

```
shopware:
  filesystem:
    private:
      visibility: "private"
      type: "bunnycdn"
      config:
        endpoint: "https://storage.bunnycdn.com"
        storageName: "..."
        subfolder: ""
        apiKey: "..."
        useGarbage: true
        neverDelete: false
```
