### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by carstenjaksch** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#64]
### Question

Hi there,

I am getting following CORS error in the console:

> Access to font at 'https://shopware.domain.tld/theme/018d5ad673eb70e59a3adb84f83de5dc/assets/font/Inter-Variable-Roman-Latin.woff2' from origin 'https://storefront.domain.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

As you may see, we use different domains for Shopware and the different sales channels (each sales channel with a different domain).

Deactivating your extension solves the issue. My first thought was that this is a Shopware issue. But they fixed it: https://issues.shopware.com/issues/NEXT-10560

However, your extension somehow adds the domain in front of the font asset url again – leading to the above error.

I found this issue here, but that seems in the context of active theme assets on the CDN: https://github.com/FriendsOfShopware/FroshPlatformBunnycdnMediaStorage/issues/51

This setting is disabled in our Shopware installation, theme assets are stored on the local file system.

So how do we fix that? The default Shopware behavior would be nice: Loading assets from the actual visited domain (current request).

I tried to remove the "theme" and "asset" config parts from bunnycdn_config.yml, but that results in a 500 error.

**Comment by tinect** [comment]
You have activated or set a url for asset and theme, that results in the url to be changed by shopware behaviour. Nothing related to this plugin, but with your settings.

Manipulating the yml should result in correct data. You have to define all filesystems. Removing one will throw a default shopware exception.
If you like to check your config in plugin you can remove the yml file. It is just created when you save the plugins setting.

Additionally, you might find solutions by checking settings within BunnyCDN regarding cors in your pull-zone-settings.


Summary:
- remove bunnycdn_config.yml to access admin again
- check your plugin config
- check your config at bunnycdn
- resave the plugin-config to have bunnycdn_config.yml re-generated

**Comment by carstenjaksch** [comment]
I think the generated config file is not quite correct, if a filesystem is set to local.

Please see the two objects "theme" and "asset" at the end. `domain.tld` refers to the Shopware domain.

The extension generates the local config with the Shopware domain in "url". That triggers the CORS error.
I tried to remove the domain and instead "url" is an empty string. Now the error is gone.

Is there any disadvantage to set "url" to an empty string?

```yml
shopware:
  cdn: { url: "https://cdn.domain.tld" }
  filesystem:
    {
      public:
        {
          type: bunnycdn,
          url: "https://cdn.domain.tld/",
          config:
            {
              endpoint: "https://storage.bunnycdn.com",
              storageName: shops,
              subfolder: "",
              apiKey: ...,
              useGarbage: true,
              neverDelete: false,
            },
        },
      sitemap:
        {
          type: bunnycdn,
          url: "https://cdn.domain.tld/",
          config:
            {
              endpoint: "https://storage.bunnycdn.com",
              storageName: shops,
              subfolder: "",
              apiKey: ...,
              useGarbage: true,
              neverDelete: false,
            },
        },
      theme:
        {
          type: local,
          url: "https://domain.tld",
          config: { root: "%kernel.project_dir%/public" },
        },
      asset:
        {
          type: local,
          url: "https://domain.tld",
          config: { root: "%kernel.project_dir%/public" },
        },
    }
```
