### ISSUE TITLE
remove space

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#79]
### Question

remove space before shopware.yml

```
shopware:
      cdn:
          url: "https://my-really-cool-company.b-cdn.net"
      filesystem:
        public: &bunnycdn
          type: "bunnycdn"
          url: "https://my-really-cool-company.b-cdn.net"
          config:
            endpoint: "https://storage.bunnycdn.com"
            apiKey: "secret-ftp-password"
            storageName: "my-really-cool-company"
            useGarbage: true
        sitemap:
          <<: *bunnycdn
        theme:
          type: "local"
          url: ""
          config:
            root: "%kernel.project_dir%/public"
        asset:
          type: "local"
          url: ""
          config:
            root: "%kernel.project_dir%/public"
```
